name: Push Tags

on:
  push:
    tags:
    - 'v*'

jobs:
  build-job:
    name: Build
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        python: ['3.11']

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel Pillow
          pip install -U ".[tests]"
        shell: bash

      - name: Build
        run: |
          delimiter=":"
          if [[ "${{matrix.os}}" == "windows-latest" ]]; then
            delimiter=";"
          fi
          if [[ "${{matrix.os}}" == "ubuntu-latest" ]]; then
            sudo apt update && sudo apt install -y libegl1
          fi
          pyinstaller --icon src/discord_overlay/static/images/icon.ico -n discord-overlay --onefile --windowed src/discord_overlay/scripts/__init__.py --add-data "src/discord_overlay/static/${delimiter}discord_overlay/static/"
          tar -czvf discord-overlay-${{ github.ref_name}}-${{ matrix.os }}.tar.gz dist/
        shell: bash
      - name: Upload artificat
        uses: actions/upload-artifact@v3
        with:
          path: discord-overlay-${{ github.ref_name}}-${{ matrix.os }}.tar.gz

  release-job:
    name:  Release
    needs: build-job
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download artificats
        uses: actions/download-artifact@v3
      - name: Display structure of downloaded files
        run: ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          draft: true
          prerelease: false
          files: |
            artifact/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
